osint:
  label: OSINT
  permalink: /osint
  description: Inteligencia de fuentes abiertas (Open Source Intelligence).

investigation:
  label: Investigacion
  permalink: /investigation
  description: Metodos, flujos de trabajo y verificacion para investigaciones OSINT.

verification:
  label: Verificacion
  permalink: /verification
  description: Tecnicas para validar evidencias, reducir falsos positivos y documentar incertidumbre.

history:
  label: Historia
  permalink: /history
  description: Origenes, evolucion y contexto historico de herramientas y metodologias.

tradecraft:
  label: Tradecraft
  permalink: /tradecraft
  description: Tecnicas y buenas practicas para investigar con rigor (y sin atajos).

privacy:
  label: Privacidad
  permalink: /privacy
  description: Consideraciones eticas, minimizacion de datos y proteccion de la privacidad.

tools:
  label: Herramientas
  permalink: /tools
  description: Software, plataformas y utilidades para recopilacion y analisis OSINT.

recon:
  label: Reconocimiento
  permalink: /recon
  description: "Reconocimiento OSINT con enfoque defensivo: inventario de activos, superficie expuesta y validacion."

automation:
  label: Automatizacion
  permalink: /automation
  description: "Automatizacion responsable de tareas OSINT (recoleccion, normalizacion, trazabilidad y repeticion)."

link-analysis:
  label: Analisis de enlaces
  permalink: /link-analysis
  description: Metodologias y tecnicas para modelar relaciones (grafos) y extraer senales utiles.

geoint:
  label: GEOINT
  permalink: /geoint
  description: Inteligencia geoespacial y analisis de imagenes satelitales.

socmint:
  label: SOCMINT
  permalink: /socmint
  description: Inteligencia de redes sociales y analisis de perfiles digitales.

opsec:
  label: OPSEC
  permalink: /opsec
  description: Seguridad operativa para investigar con minima exposicion y trazabilidad.
